/*
 * Production API
 *
 * API exposing endpoints for managing well headers and daily production.
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing DailyProductionInput
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DailyProductionInputTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DailyProductionInput
        //private DailyProductionInput instance;

        public DailyProductionInputTests()
        {
            // TODO uncomment below to create an instance of DailyProductionInput
            //instance = new DailyProductionInput();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DailyProductionInput
        /// </summary>
        [Fact]
        public void DailyProductionInputInstanceTest()
        {
            // TODO uncomment below to test "IsType" DailyProductionInput
            //Assert.IsType<DailyProductionInput>(instance);
        }


        /// <summary>
        /// Test the property 'Uwi'
        /// </summary>
        [Fact]
        public void UwiTest()
        {
            // TODO unit test for the property 'Uwi'
        }
        /// <summary>
        /// Test the property 'Datetime'
        /// </summary>
        [Fact]
        public void DatetimeTest()
        {
            // TODO unit test for the property 'Datetime'
        }
        /// <summary>
        /// Test the property 'LiquidRate'
        /// </summary>
        [Fact]
        public void LiquidRateTest()
        {
            // TODO unit test for the property 'LiquidRate'
        }
        /// <summary>
        /// Test the property 'OilProductionRate'
        /// </summary>
        [Fact]
        public void OilProductionRateTest()
        {
            // TODO unit test for the property 'OilProductionRate'
        }
        /// <summary>
        /// Test the property 'GasProductionRate'
        /// </summary>
        [Fact]
        public void GasProductionRateTest()
        {
            // TODO unit test for the property 'GasProductionRate'
        }
        /// <summary>
        /// Test the property 'WaterProductionRate'
        /// </summary>
        [Fact]
        public void WaterProductionRateTest()
        {
            // TODO unit test for the property 'WaterProductionRate'
        }
        /// <summary>
        /// Test the property 'Choke'
        /// </summary>
        [Fact]
        public void ChokeTest()
        {
            // TODO unit test for the property 'Choke'
        }
        /// <summary>
        /// Test the property 'GasOilRatio'
        /// </summary>
        [Fact]
        public void GasOilRatioTest()
        {
            // TODO unit test for the property 'GasOilRatio'
        }
        /// <summary>
        /// Test the property 'WaterCut'
        /// </summary>
        [Fact]
        public void WaterCutTest()
        {
            // TODO unit test for the property 'WaterCut'
        }
        /// <summary>
        /// Test the property 'TubingPressure'
        /// </summary>
        [Fact]
        public void TubingPressureTest()
        {
            // TODO unit test for the property 'TubingPressure'
        }
        /// <summary>
        /// Test the property 'CasingPressure'
        /// </summary>
        [Fact]
        public void CasingPressureTest()
        {
            // TODO unit test for the property 'CasingPressure'
        }
        /// <summary>
        /// Test the property 'GasInjectionRate'
        /// </summary>
        [Fact]
        public void GasInjectionRateTest()
        {
            // TODO unit test for the property 'GasInjectionRate'
        }
        /// <summary>
        /// Test the property 'OperatingFrequency'
        /// </summary>
        [Fact]
        public void OperatingFrequencyTest()
        {
            // TODO unit test for the property 'OperatingFrequency'
        }
        /// <summary>
        /// Test the property 'StrokesPerMinute'
        /// </summary>
        [Fact]
        public void StrokesPerMinuteTest()
        {
            // TODO unit test for the property 'StrokesPerMinute'
        }
        /// <summary>
        /// Test the property 'DowntimeHours'
        /// </summary>
        [Fact]
        public void DowntimeHoursTest()
        {
            // TODO unit test for the property 'DowntimeHours'
        }
        /// <summary>
        /// Test the property 'DowntimeCode'
        /// </summary>
        [Fact]
        public void DowntimeCodeTest()
        {
            // TODO unit test for the property 'DowntimeCode'
        }

    }

}
