"""
    Production API

    API exposing endpoints for managing well headers and daily production.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.daily_production_input import DailyProductionInput


class TestDailyProductionInput(unittest.TestCase):
    """DailyProductionInput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDailyProductionInput(self):
        """Test DailyProductionInput"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DailyProductionInput()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
