"""
    Production API

    API exposing endpoints for managing well headers and daily production.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.well_header_api import WellHeaderApi  # noqa: E501


class TestWellHeaderApi(unittest.TestCase):
    """WellHeaderApi unit test stubs"""

    def setUp(self):
        self.api = WellHeaderApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_production_add_update_well_headers(self):
        """Test case for production_add_update_well_headers

        Bulk Add / Update WellHeader Data  # noqa: E501
        """
        pass

    def test_production_delete_well_header(self):
        """Test case for production_delete_well_header

        Delete Single Well Header  # noqa: E501
        """
        pass

    def test_production_get_well_header(self):
        """Test case for production_get_well_header

        Fetch Single Well Header  # noqa: E501
        """
        pass

    def test_production_get_well_headers(self):
        """Test case for production_get_well_headers

        Fetch Multiple Well Headers  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
