"""
    Production API

    API exposing endpoints for managing well headers and daily production.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.well_header_input import WellHeaderInput


class TestWellHeaderInput(unittest.TestCase):
    """WellHeaderInput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWellHeaderInput(self):
        """Test WellHeaderInput"""
        # FIXME: construct object with mandatory attributes with example values
        # model = WellHeaderInput()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
