/*
 * Production API
 *
 * API exposing endpoints for managing well headers and daily production.
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Org.OpenAPITools.Client;
using Org.OpenAPITools.Api;
// uncomment below to import models
//using Org.OpenAPITools.Model;

namespace Org.OpenAPITools.Test.Api
{
    /// <summary>
    ///  Class for testing DailyProductionApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class DailyProductionApiTests : IDisposable
    {
        private DailyProductionApi instance;

        public DailyProductionApiTests()
        {
            instance = new DailyProductionApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DailyProductionApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' DailyProductionApi
            //Assert.IsType<DailyProductionApi>(instance);
        }

        /// <summary>
        /// Test ProductionAddDaily
        /// </summary>
        [Fact]
        public void ProductionAddDailyTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //List<DailyProductionInput> dailyProductionInput = null;
            //var response = instance.ProductionAddDaily(dailyProductionInput);
            //Assert.IsType<List<DailyProduction>>(response);
        }

        /// <summary>
        /// Test ProductionDeleteDaily
        /// </summary>
        [Fact]
        public void ProductionDeleteDailyTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string xid = null;
            //var response = instance.ProductionDeleteDaily(xid);
            //Assert.IsType<bool>(response);
        }

        /// <summary>
        /// Test ProductionGetDaily
        /// </summary>
        [Fact]
        public void ProductionGetDailyTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string uwi = null;
            //DateTime? startDate = null;
            //DateTime? endDate = null;
            //int? page = null;
            //int? limit = null;
            //var response = instance.ProductionGetDaily(uwi, startDate, endDate, page, limit);
            //Assert.IsType<List<DailyProduction>>(response);
        }
    }
}
